-- CREAR BASE DE DATOS EMPLEADOS
CREATE DATABASE EmppleadosApi;

--CREAR TABLA DE EMPLEADOS
CREATE TABLE Empleados(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    APELLIDO VARCHAR(255) NOT NULL,
    ESTATUS BOOLEAN NOT NULL,
    PUESTO VARCHAR(255) NOT NULL,
    SUELDO INTEGER NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL
);